import { useId } from 'react';
import { RotateCw, Layers } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import { generateSku } from './generateSku';
import { Link } from 'react-router-dom';
import { ADMIN_BASE } from '../../config/adminPath';
import { Button, Input, Modal, Select, Textarea } from '../../components/ui';

const LINK_CLASSES = 'inline-flex items-center gap-1 min-h-9 text-xs font-semibold text-primary-600 dark:text-primary-400 hover:underline cursor-pointer';

export const ProductFormModal = ({
  categories,
  editingProduct,
  formData,
  handleSubmit,
  setFormData,
  setShowModal
}) => {
  const { t } = useLanguage();
  const formId = useId();
  const close = () => setShowModal(false);

  return (
    <Modal
      isOpen
      onClose={close}
      size="lg"
      title={editingProduct ? t('editProduct') : t('addProduct')}
      footer={(
        <>
          <Button variant="secondary" onClick={close}>{t('cancel')}</Button>
          <Button type="submit" form={formId}>{editingProduct ? t('update') : t('create')}</Button>
        </>
      )}
    >
      <form id={formId} onSubmit={handleSubmit} className="space-y-4">
        {/* Product ID (SKU) - Auto-generated with regenerate button */}
        <div className="space-y-1">
          <Input
            label={`${t('productId')} *`}
            hint={t('autoGenerated')}
            type="text"
            required
            value={formData.sku}
            onChange={(e) => setFormData({ ...formData, sku: e.target.value.toUpperCase() })}
            className="font-mono font-bold tracking-wide uppercase"
            placeholder="PRD-123456"
          />
          <button
            type="button"
            onClick={() => setFormData(prev => ({ ...prev, sku: generateSku() }))}
            className={LINK_CLASSES}
          >
            <RotateCw className="w-3 h-3" aria-hidden="true" />
            <span>{t('regenerateId')}</span>
          </button>
        </div>

        {/* Bilingual Names */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Input
            label={`${t('productNameDe')} *`}
            type="text"
            required
            dir="ltr"
            value={formData.nameDe}
            onChange={(e) => setFormData({ ...formData, nameDe: e.target.value })}
            placeholder="z. B. Basmati Reis 25kg"
          />
          <Input
            label={`${t('productNameAr')} *`}
            type="text"
            required
            dir="rtl"
            value={formData.nameAr}
            onChange={(e) => setFormData({ ...formData, nameAr: e.target.value })}
            placeholder="مثال: أرز بسمتي 25 كغ"
          />
        </div>

        {/* Category Dropdown Selection */}
        <div className="space-y-1">
          <Select
            label={t('category')}
            value={formData.categoryId}
            onChange={(e) => setFormData({ ...formData, categoryId: e.target.value })}
          >
            <option value="">-- {t('selectCategory')} --</option>
            {categories.map((c) => (
              <option key={c.id} value={c.id}>
                {c.nameDe} — {c.nameAr}
              </option>
            ))}
          </Select>
          <Link to={`${ADMIN_BASE}/catalogs`} target="_blank" className={LINK_CLASSES}>
            <Layers className="w-3 h-3" aria-hidden="true" />
            <span>{t('newCatalogQuick')}</span>
          </Link>
        </div>

        {/* Price & Stock */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Input
            label={`${t('b2bPrice')} *`}
            type="number"
            step="0.01"
            min="0"
            required
            value={formData.b2bPrice}
            onChange={(e) => setFormData({ ...formData, b2bPrice: e.target.value })}
            placeholder="19.99"
          />
          <Input
            label={`${t('stock')} *`}
            type="number"
            min="0"
            required
            value={formData.stock}
            onChange={(e) => setFormData({ ...formData, stock: parseInt(e.target.value, 10) || 0 })}
            placeholder="50"
          />
        </div>

        {/* Image URL */}
        <Input
          label={t('imageUrl')}
          type="url"
          value={formData.imageUrl}
          onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
          placeholder="https://images.unsplash.com/..."
        />

        {/* Bilingual Descriptions */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Textarea
            label={t('descriptionDe')}
            rows="2"
            dir="ltr"
            value={formData.descriptionDe}
            onChange={(e) => setFormData({ ...formData, descriptionDe: e.target.value })}
            placeholder="Produktspezifikationen, Verpackungseinheiten..."
          />
          <Textarea
            label={t('descriptionAr')}
            rows="2"
            dir="rtl"
            value={formData.descriptionAr}
            onChange={(e) => setFormData({ ...formData, descriptionAr: e.target.value })}
            placeholder="المواصفات، عبوات الجملة، شروط التوريد..."
          />
        </div>
      </form>
    </Modal>
  );
};
