import { Package, X, RotateCw, Layers } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import { generateSku } from './generateSku';
import { Link } from 'react-router-dom';
import { ADMIN_BASE } from '../../config/adminPath';

export const ProductFormModal = ({
  categories,
  editingProduct,
  formData,
  handleSubmit,
  setFormData,
  setShowModal
}) => {
  const { t } = useLanguage();

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center z-50 p-3 sm:p-4 animate-in fade-in duration-200">
      <div className="bg-white dark:bg-gray-900 rounded-2xl p-4 sm:p-7 w-full max-w-xl max-h-[90dvh] overflow-y-auto border border-slate-200 dark:border-gray-800 shadow-2xl">
        <div className="flex items-center justify-between pb-3 sm:pb-4 mb-4 sm:mb-5 border-b border-slate-100 dark:border-gray-800">
          <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Package className="w-5 h-5 text-primary-600 dark:text-primary-400" />
            <span>{editingProduct ? t('editProduct') : t('addProduct')}</span>
          </h2>
          <button
            onClick={() => setShowModal(false)}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-gray-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Product ID (SKU) - Auto-generated with regenerate button */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                {t('productId')} *
              </label>
              <button
                type="button"
                onClick={() => setFormData(prev => ({ ...prev, sku: generateSku() }))}
                className="flex items-center gap-1 text-[11px] font-semibold text-primary-600 dark:text-primary-400 hover:underline"
              >
                <RotateCw className="w-3 h-3" />
                <span>{t('regenerateId')}</span>
              </button>
            </div>
            <input
              type="text"
              required
              value={formData.sku}
              onChange={(e) => setFormData({ ...formData, sku: e.target.value.toUpperCase() })}
              className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 font-mono font-bold tracking-wide transition uppercase"
              placeholder="PRD-123456"
            />
            <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-1">
              {t('autoGenerated')}
            </p>
          </div>

          {/* Bilingual Names */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('productNameDe')} *
              </label>
              <input
                type="text"
                required
                dir="ltr"
                value={formData.nameDe}
                onChange={(e) => setFormData({ ...formData, nameDe: e.target.value })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition"
                placeholder="z. B. Basmati Reis 25kg"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('productNameAr')} *
              </label>
              <input
                type="text"
                required
                dir="rtl"
                value={formData.nameAr}
                onChange={(e) => setFormData({ ...formData, nameAr: e.target.value })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition text-right"
                placeholder="مثال: أرز بسمتي 25 كغ"
              />
            </div>
          </div>

          {/* Category Dropdown Selection */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                {t('category')}
              </label>
              <Link
                to={`${ADMIN_BASE}/catalogs`}
                target="_blank"
                className="text-[11px] font-semibold text-primary-600 dark:text-primary-400 hover:underline flex items-center gap-1"
              >
                <Layers className="w-3 h-3" />
                <span>{t('newCatalogQuick')}</span>
              </Link>
            </div>
            <select
              value={formData.categoryId}
              onChange={(e) => setFormData({ ...formData, categoryId: e.target.value })}
              className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition text-sm"
            >
              <option value="">-- {t('selectCategory')} --</option>
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.nameDe} — {c.nameAr}
                </option>
              ))}
            </select>
          </div>

          {/* Price & Stock */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('b2bPrice')} *
              </label>
              <input
                type="number"
                step="0.01"
                min="0"
                required
                value={formData.b2bPrice}
                onChange={(e) => setFormData({ ...formData, b2bPrice: e.target.value })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition"
                placeholder="19.99"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('stock')} *
              </label>
              <input
                type="number"
                min="0"
                required
                value={formData.stock}
                onChange={(e) => setFormData({ ...formData, stock: parseInt(e.target.value, 10) || 0 })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition"
                placeholder="50"
              />
            </div>
          </div>

          {/* Image URL */}
          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
              {t('imageUrl')}
            </label>
            <input
              type="url"
              value={formData.imageUrl}
              onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
              className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition text-sm"
              placeholder="https://images.unsplash.com/..."
            />
          </div>

          {/* Bilingual Descriptions */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('descriptionDe')}
              </label>
              <textarea
                rows="2"
                dir="ltr"
                value={formData.descriptionDe}
                onChange={(e) => setFormData({ ...formData, descriptionDe: e.target.value })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition text-sm"
                placeholder="Produktspezifikationen, Verpackungseinheiten..."
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                {t('descriptionAr')}
              </label>
              <textarea
                rows="2"
                dir="rtl"
                value={formData.descriptionAr}
                onChange={(e) => setFormData({ ...formData, descriptionAr: e.target.value })}
                className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-gray-950 border border-slate-200 dark:border-gray-750 rounded-xl text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary-500 transition text-sm text-right"
                placeholder="المواصفات، عبوات الجملة، شروط التوريد..."
              />
            </div>
          </div>

          <div className="flex flex-col-reverse xs:flex-row items-center justify-end gap-2 sm:gap-3 pt-4 border-t border-slate-100 dark:border-gray-800">
            <button
              type="button"
              onClick={() => setShowModal(false)}
              className="w-full xs:w-auto px-4 py-2.5 text-xs sm:text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-gray-800 rounded-xl transition touch-manipulation cursor-pointer text-center"
            >
              {t('cancel')}
            </button>
            <button
              type="submit"
              className="w-full xs:w-auto px-5 py-2.5 bg-primary-600 hover:bg-primary-700 text-white text-xs sm:text-sm font-medium rounded-xl shadow-sm transition touch-manipulation cursor-pointer text-center"
            >
              {editingProduct ? t('update') : t('create')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
